kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: golang
  annotations:
    description: Construir una aplicación en lenguaje go
    iconClass: icon-golang
    tags: 'golang'
    template.openshift.io/bindable: 'false'
    template.openshift.io/provider-display-name: 'Red Hat, Inc.'
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: '${APPLICATION_NAME}'
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: '${APPLICATION_NAME}'
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: '${APPLICATION_NAME}-builder'
      labels:
        app: '${APPLICATION_NAME}'
    spec: {}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: '${APPLICATION_NAME}-builder'
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${APPLICATION_NAME}-builder:latest'
      postCommit: {}
      resources: {}
      source:
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        contextDir: '${SOURCE_REPOSITORY_DIR}'
        type: git
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      runPolicy: Serial
      triggers:
        - type: ConfigChange
        - type: ImageChange
    status:
      lastVersion: 0
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: '${APPLICATION_NAME}'
        app.openshift.io/runtime: golang
      name: '${APPLICATION_NAME}'
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
    spec:
      paused: true
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: '${APPLICATION_NAME}'
      strategy:
        rollingParams: null
        type: Rolling
      template:
        metadata:
          labels:
            app: '${APPLICATION_NAME}'
        spec:
          containers:
              image: '${APPLICATION_NAME}-builder:${IMAGE_TAG}'
              imagePullPolicy: Always
              name: '${APPLICATION_NAME}'
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
      triggers:
        - type: ConfigChange
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: SOURCE URL
    description: The source URL for the application
    value: 'https://github.com/branddcast/godror.git'
    required: true
  - name: SOURCE_REPOSITORY_REF
    displayName: SOURCE BRANCH
    description: The branch name for the application
    value: main
    required: true
  - name: SOURCE_REPOSITORY_DIR
    displayName: SOURCE DIRECTORY
    description: The location within the source repo of the application
    value: .
    required: true
  - name: APPLICATION_NAME
    displayName: NAME
    description: The name for the application
    value: godror
  - name: IMAGE_TAG
    displayName: Ex latest
    description: Image Tag
    value: latest
    required: true